### ISSUE TITLE
Choose the css framework

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/internships#11]
I would like you to choose a frontend CSS framework to work with:
* [Tailwind](https://tailwindcss.com/) (with [Tailwind UI](https://tailwindui.com/))
* [Bootstrap](https://getbootstrap.com/)
* something else?

The result of this task should be to choose one technology.

**Comment by LukaszPodlipski** [comment]
Tailwind looks promising.

**Comment by plencka** [comment]
I agree that Tailwind is a good pick. It provides more utility classes than Bootstrap, which will make it easier to create webpage similar to the mock-up given in #3.
