### ISSUE TITLE
Map on deploy is not loading style correctly

### ISSUE THREAD

**Issue by brzozka** [blumilksoftware/internships#112]
As in title.

**Comment by krzysztofrewak** [comment]
For it's not loading at all:
![obraz](https://user-images.githubusercontent.com/10898728/128474754-30c6f4ca-7d05-416d-bbdf-9227c071cb20.png)

**Comment by krzysztofrewak** [comment]
Secret for `VUE_APP_MAPBOX_STYLE_URL` added.
