### ISSUE TITLE
Adjust map style to match with website CSS

### ISSUE THREAD

**Issue by plencka** [blumilksoftware/internships#120]
As in title. Currently it clashes with the design and is too bright for the eyes:

![Screenshot from 2021-08-11 13 37 53](https://user-images.githubusercontent.com/49527545/129022413-ab9de60a-a834-4dd5-93ed-dee1b230a647.png)

Maybe something toned down, with not so bright neon colors? Main color of such style could be changed to have light blue/purple tint instead of dull brown.

![Screenshot from 2021-08-11 13 38 50](https://user-images.githubusercontent.com/49527545/129022529-e03958c5-03b6-4520-ad47-8e9b9db39a4e.png)

**Comment by plencka** [comment]
It is important to keep the website consistent.

We should replace current style, because it is not maintained by any currently active contributor.
For current website design, the above Frank style seems fitting to me.

**Comment by plencka** [comment]
It seems we need to change style anyway, because current one was deleted.

**Comment by sbanasiak** [comment]
In #154 , the site style was updated to https://www.mapbox.com/maps/light which matches the current site design, so this issue can be closed.
![Screenshot from 2022-08-05 12-28-14](https://user-images.githubusercontent.com/92038757/183077975-dc06aa41-0eec-4bcf-88bb-153047a0b3a2.png)
