### ISSUE TITLE
Create functionality to process `isPaid` values

### ISSUE THREAD

**Issue by brzozka** [blumilksoftware/internships#129]
As referenced in #90 currently isPaid field stores YES/NO string values, so we need some kind of filtering to get boolean value from it. PHP is not my thing, and I think it's one of the core components when it comes to filters, so waiting for later implementation will be a problem. I will handle it in the frontend part.

**Comment by plencka** [comment]
The new database will likely contain properly formatted values. It shouldn't be done in the frontend.

Maybe we will retire this field altogether, a payment is usually not discussed for internships.
