### ISSUE TITLE
Fix docker/deploy configs to work simultaneously

### ISSUE THREAD

**Issue by brzozka** [blumilksoftware/internships#133]
As in title, for now changing publicPath to /internships/ as github pages requires causes problems with local build with docker.

**Comment by MatArasim** [comment]
Docker/deploye configs will be rewritten to new ones, cuz current docker config dont even work properly, after that problem will be probably solved.

**Comment by plencka** [comment]
This issue should be closed anyway without considering rewrite. 
We already decided to use Laravel.

From what I remember, Github Pages [at least by default / free tier?] will not handle all requests made by client, so they will likely not be used anymore.
