### ISSUE TITLE
Github pages deploy fix.

### ISSUE THREAD

**Issue by brzozka** [blumilksoftware/internships#137]
There are two problems with backend deploy as of now.
1.  Deploy can't read  env file
![image](https://user-images.githubusercontent.com/39692087/131344316-411af145-33cb-4531-83aa-c918ebd58dde.png)

2. Some backend function is looking for `documents.csv` file in `resources/faculities/wydzial-humanistyczny/documents/documents.csv` and `resources/faculities/wydzial-zdrowie-kultura/documents/documents.csv`
but they don't exist so I will put the same test file as in wydzial-techniczny

**Comment by plencka** [comment]
> 2. Some backend function is looking for `documents.csv` file in `resources/faculities/wydzial-humanistyczny/documents/documents.csv` and `resources/faculities/wydzial-zdrowie-kultura/documents/documents.csv`

If populate command runs properly, it should resolve this issue. The resulting file will have empty records, but it will have column headers defined.

**Comment by brzozka** [comment]
Well then populate command doesn't run properly, because it only generates file for `wydzial-techniczny`

![image](https://user-images.githubusercontent.com/39692087/131511441-a519e452-5b23-4da6-a189-efa9cfe4dc52.png)
