### ISSUE TITLE
Cleanup issues board and prepare new tasks

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/internships#143]
This project will be refactored into Laravel application during this summer internships programme.

I would like to see interns to check every opened issue and decide what should be really done and what should be closed. For 100% we will open new tasks for new scope.

**Comment by plencka** [comment]
Every currently opened task has been commented on.

The only thing left is to figure out if our observations are valid. And to create new tasks according to things discussed during the first meeting.

I think the prority is to close unnecessary issues before opening new ones.

**Comment by sbanasiak** [comment]
All outdated tasks except this one have been reviewed and closed.
