### ISSUE TITLE
Update the readme file with instructions on how to run this project

### ISSUE THREAD

**Issue by brzozka** [blumilksoftware/internships#16]
As in title

**Comment by plencka** [comment]
This is an ongoing task and it's worth leaving it as it is.
It appears current readme is not fully valid and frontend does not run properly from provided instructions.

**Comment by EwelinaLasowy** [comment]
I'd like to close ongoing tasks - it has no sense for making this. And I think that instructions in readme file will be updated, when @krzysztofrewak cleans `docker-compose.yml` file.

**Comment by plencka** [comment]
Alright. I think we should create new issues for bugs found in readme instructions.
