### ISSUE TITLE
Separate lint github action

### ISSUE THREAD

**Issue by plencka** [blumilksoftware/internships#177]
Right now we have one action that runs pretty much everything, except for title check.

I think we should split this action into:
- lint checking for js, css and other frontend stuff
- codestyle checking for php
- install dependencies for frontend
- install dependencies for backend

The action does not continue after it fails, so we don't know what happens next and we need to run it multiple times.

**Comment by krzysztofrewak** [comment]
It would be nice to exclude - for example - changes of JS files in PHP linter. We have this covered here: https://github.com/blumilksoftware/toby/blob/main/.github/workflows/test-and-lint-php.yml#L12
