### ISSUE TITLE
Create the landing page

### ISSUE THREAD

**Issue by brzozka** [blumilksoftware/internships#28]
As in title. We want user to see the landing page with some background and possibly buttons for user to choose his faculty/department

**Comment by LukaszPodlipski** [comment]
![Zrzut ekranu 2021-07-12 o 10 11 50](https://user-images.githubusercontent.com/73656796/125258475-ac95c880-e2fe-11eb-82ba-4da741892fd9.png)
Really simple LP with a faculty selector.

**Comment by LukaszPodlipski** [comment]
Really simple LP with a faculty selector.

![Zrzut ekranu 2021-07-12 o 10 47 59](https://user-images.githubusercontent.com/73656796/125258886-0eeec900-e2ff-11eb-94f8-2c805c4f6479.png)

**Comment by LukaszPodlipski** [comment]
And corrected last sentence " Jest to projekt opern source - każdy może skorzystać w pełni za darmo."
