### ISSUE TITLE
Node isn't containerized and runs from host machine.

### ISSUE THREAD

**Issue by plencka** [blumilksoftware/internships#35]
As in title.

**Comment by plencka** [comment]
It seems node issue was reintroduced again, related to hooks. I ran all current instructions in Readme, but an error is thrown after rebuilding npm and gettting new package.lock file.
![Screenshot from 2021-07-22 14 01 48](https://user-images.githubusercontent.com/49527545/126636040-e78c090a-3d19-40a7-8f28-362fb4f292b4.png)

**Comment by mtracz** [comment]
Probably you need to run this command from node container if you are using GIT on the host machine.

Something like that, or try with docker run command
```
"gitHooks": {
    "pre-commit": "docker-compose exec node npm lint-staged"
  },
  ```

**Comment by brzozka** [comment]
Yeah this git hook was installed by Vue CLI while setting up project at the beginning, we have lint on save so we don't really need linting on commit. I wanted to delete this but I was busy with main page fixes. I will delete this now, but thanks for help and clearing it up @mtracz
