### ISSUE TITLE
Popositon to the nginx config file

### ISSUE THREAD

**Issue by kamilniemczycki** [blumilksoftware/internships#48]
I propose to change the second line in [nginx.conf](https://github.com/blumilksoftware/internships/blob/e03e373f6f8975d5eabfe11a4680ecda4779965a/environment/nginx.conf#L2)
from:
```
    root /application/public;
```
to:
```
    root /application/dist;
```

**Because. I assume that the project is finally built as follows:**

1. Installing dependencies for the frontend as proposed in #47 
```
$> docker-compose exec node yarn install
```
2. Installing dependencies for the backend
```
$> docker-compose exec php composer install
```
3. Building a backend
```
$> docker-compose exec php composer populate
$> docker-compose exec php composer build
```
4. Building a frontend
```
$> docker-compose exec node yarn build
```

Finally, everything in the public folder will be moved to dist + generated files.

**Comment by krzysztofrewak** [comment]
Hi, @kamilniemczycki! I think you can create a pull request with proposed changes. In the worst case scenario it will be discussed and closed. ;)
