### ISSUE TITLE
Choose the content delivery technology

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/internships#5]
In the ideal world I would like to have an easy-maintainable file with all the companies in one place (let's say in `resources` directory). It would looks like this:

```json
{
  "companies": [
    {
      "name": "Blumilk sp. z o.o.",
      "display": "Blumilk",
      "logo": "/images/companies/blumilk.png",
      "interests": [
        "developers"
      ],
      "location": {
        "city": "Legnica",
        "address": "ul. Najświętszej Marii Panny 5F/5",
        "coordinates": {
          "lat": 51.20872689991233,
          "lng": 16.16372241766431
        }
      },
      "about": "Lorem ipsum...",
      "links": {
        "website": "https://blumilk.pl/",
        "linkedin": "https://linkedin.com/company/blumilksoftware/",
        "facebook": "https://facebook.com/blumilksoftware/"
      }
    }
  ]
}
```

Or maybe it should be a CSV file easy to run from Excel? It should be discussed.

We don't want to maintain aby database or anything like that and we want our application to be fast as hell. I would like generate at least few files from these resources (eg. list of cities or maybe some more complex mapping like "companies in powiat bolesławiecki" or something). 

A reference could be find [here](https://browary.rewak.pl/) and [here](https://github.com/krzysztofrewak/browary).

Furthermore, all the static content like name of the university, testimionals and thing like that should be also contained in resource files. These could be markdown pages probably.

The result of this task should be to choose one technology.

**Comment by plencka** [comment]
We should consider CSV format for this task. Exporting values from Excel file would be user friendly.

PHP has built-in functions for parsing those, so I think we can work with that.
