### ISSUE TITLE
Choose the map provider technology

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/internships#6]
I would like to have a map with all companies (and probably university and user current location) pinned. There are some map providers we could use, including:
* [Leaflet](https://leafletjs.com/)
* [Mapbox](https://www.mapbox.com/)
* [Google Maps](https://developers.google.com/maps/documentation)

The map should be
* ready to handle at least hundreds of pins,
* working fine on desktop and mobile devices,
* at least little customizable.

The result of this task should be to choose one technology.

**Comment by LukaszPodlipski** [comment]
I have little experience with Leaflet and it is ok, but Mapbox has some UX features that are better. So I choose Mapbox.

**Comment by plencka** [comment]
Yeah, Mapbox seems to provide more options for map customization. It also has plenty of free monthly requests, which should be enough for development.

**Comment by krzysztofrewak** [comment]
> Yeah, Mapbox seems to provide more options for map customization. It also has plenty of free monthly requests, which should be enough for development.

And in the worst case scenario, you can generatre multiple accounts for development. ;)
