### ISSUE TITLE
Process the list of the companies

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/internships#7]
[Here](http://www.praktyki.pwsz.legnica.edu.pl/strona-364-1-2) you can find a docx file with the list of companies where students can find intership programmes:

![obraz](https://user-images.githubusercontent.com/10898728/123844309-25664f00-d913-11eb-8b6c-4e91e0f2c4b3.png)

Easy part is to convert it to something more maintainable (which will be chosen in #5). Hard part is to:
- [x] check if all these companies really exists;
- [x] manually (or programatically?) fetch coordinates for all these places;
- [x] fix all misspelled names and street names
- [x] split general entires like "Urzędy Miasta" into separate entires like "Urząd Miasta Legnica", "Urząd Miejski Chojnów", etc.

**Comment by plencka** [comment]
If we decide to use CSV format, we can use Google Spreadsheets to work on the file together.

I checked how to fetch coordinates from addresses and the most straightforward solution would be an addon for the docs called Geocoding by SmartMonkey. It uses Google Maps API and it allows us to run function directly in spreadsheet.

**Comment by plencka** [comment]
Ok, I generated the spreadsheet for this task available under [this link](https://docs.google.com/spreadsheets/d/1qMQX8xGkkde05kPDx5xD-ENCIiAga65C9-VKf6LWyu4/edit?usp=sharing). I gave you editing rights. If I messed up permissions, you can always request them.

The major issue of this addon is that we cannot move the location of the address, and I cannot find an option to configure it. We might reconsider how to find coordinates, but I'm leaving it this way for this moment.

To generate coordinates, simply go to 'addons (pl. Dodatki)' in upper context menu and use "Geocoding by SmartMonkey -> Geocode". I'm not sure if you need to download this addon, or if it downloads automatically/

**Comment by plencka** [comment]
We've finished parsing the data. Now we need to decide if we want to export it to .csv manually, or if we want to export data from spreadsheet to csv through some script.

There's PhpSpreadsheet library, which can read xlsx-related formats. This way, user will have to do fewer actions to configure website project.

**Comment by krzysztofrewak** [comment]
CSV is nice, because we can store it in the repository and edit it even from the browser. XLSX file is a clusterfuck with that.

**Comment by krzysztofrewak** [comment]
@plencka, I think you can open the first pull request with this CSV file. It could be placed in `/resources/companies.csv` or maybe `/resources/companies/wt.csv` for "Wydział Techniczny". Please remember about our conventions about branch naming, PR naming and commit naming. ;)
