### ISSUE TITLE
Compile Resources into Static API on Deploy.

### ISSUE THREAD

**Issue by plencka** [blumilksoftware/internships#76]
As in title. 

We need to make deploy to run `composer build` to create .json files from resources, and to copy data like documents.

For this to even work, we need to fill data for other faculties. It's better to not run `composer populate`, because it will result in empty data sets, which might appear to the end user as unintended.

**Comment by MatArasim** [comment]
Project will be running with data base and laravel, there is no need to make deploy to run composer build to create .json files from resources.
